parameters:
#    custom_web.example.class: Custom\WebBundle\Example
    topxia_services:
        'Course.CourseService' : 'Custom\Service\Course\Impl\CourseServiceImpl'
    topxia_daos:
        'Course.CourseDao' : 'Custom\Service\Course\Dao\Impl\CourseDaoImpl'
services:
#    custom_web.example:
#        class: %custom_web.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]

    custom.twig.web_extension:
        class: Custom\WebBundle\Twig\Extension\WebExtension
        arguments:    [@service_container]
        tags:
            - { name: twig.extension }